# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ee3cdba22f8ae34d8b336208dfa44cf041aa66ed7affcfb556bd5eafc30f7cc8b6fa0d5925afbc2bc9fe304c87c9c34592516a55bc4122ff8ccb9f3c1815f090

test:
  secret_key_base: aca2b6ebdafbb8e637075b687ba0e4d4814f5b5982a2441fcdc616f00887e8ecaea4b85bcb400708394ab8e2f58a7e0f680bd6ccbab7e735fd5ce1f1e7133101

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
